#!/usr/bin/env bash
#
# Copyright 2020 Maxim Shpak <maxim.shpak@posteo.uk>
# Licensed under the MIT License. See MIT in the programme's folder for license information.

# Symlink bin command to /usr/bin
rm -f /usr/bin/Myfyrio
ln -s /usr/share/myfyrio/Myfyrio /usr/bin/Myfyrio

# Install the desktop entry
if hash desktop-file-install 2>/dev/null; then
	desktop-file-install /usr/share/applications/myfyrio.desktop
fi

